# makefile for lab04
all:	lab06 nested family math

family:	family.pl
	gplc family.pl

lab06:	lab06.pl
	gplc lab06.pl

nested:	nested.pl
	gplc nested.pl

math:	math.pl
	gplc math.pl

clean:
	rm -f lab06 nested family math
