# makefile for some C# programs

all:	sample1 sample2 sample3 sample4 sample5 sample6 sample7 lab07 

sample1:	sample1.cs
	mcs sample1.cs

sample2:	sample2.cs
	mcs sample2.cs

sample3:	sample3.cs
	mcs sample3.cs

sample4:	sample4.cs
	mcs sample4.cs

sample5:	sample5.cs
	mcs sample5.cs

sample6:	sample6.cs
	mcs sample6.cs

sample7:	sample7.cs
	mcs sample7.cs

lab07:	lab07.cs
	mcs lab07.cs

clean:	
	rm -f lab07.exe sample1.exe sample2.exe sample3.exe sample4.exe sample5.exe 
	rm -f sample6.exe sample7.exe
